// 전역 변수 설정
const $pause = document.querySelector('.pause');
const $contents = document.querySelector('.contents');
const $score = document.querySelector('.score');
const $doodle = document.getElementById('doodle');
const $bar = document.querySelector('.bar');
const $brokenBar = document.querySelector('.broken');
const $movingBar = document.querySelector('.moving');
const $disappearBar = document.querySelector('.disappear');
const $disposableBar = document.querySelector('.disposable');